trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'wordpress'
  appName: 'wordpresslc'
  resourceGroup: 'wordpresslc'
  packagePath: '$(Build.ArtifactStagingDirectory)/wordpress.zip'

steps:
# ✅ Create a 'wordpress' directory and move files inside it
- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/wordpress
    cp -r $(System.DefaultWorkingDirectory)/* $(Build.ArtifactStagingDirectory)/wordpress/
  displayName: "Create WordPress directory and copy files"

# ✅ Archive the 'wordpress' directory into a zip file
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/wordpress'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/wordpress.zip'
    replaceExistingArchive: true

# ✅ Deploy the zip file to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(appName)'
    resourceGroupName: '$(resourceGroup)'
    package: '$(packagePath)'

# ✅ Set PHP version for WordPress
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Setting PHP version to 8.0"
      az webapp config set --name $(appName) --resource-group $(resourceGroup) --linux-fx-version "PHP|8.0"
  displayName: "Set PHP version for WordPress"

# ✅ Enable MySQL extension
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Enabling MySQL extension"
      az webapp config appsettings set --name $(appName) --resource-group $(resourceGroup) --settings WEBSITE_MYSQL_ENABLED=1
  displayName: "Enable MySQL Extension for WordPress"
